{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.0.aar",
          "url": "fluttertoast_profile-1.0.aar",
          "size": 10188,
          "sha512": "43c1041b5f8359edb05e5428f3663630ed18b4926d2686e0d3e7f1f7aea5589212d3a4c379c46a7e84f06add843acbecfa2816090d3ff65e1e18b8ba1c02f666",
          "sha256": "5b15d9fba3f250dd8aa13be8e1a511b961dbb610a3d333ea5f3572c4cc97c581",
          "sha1": "26743422c796d2bc27413ad156c11c0faf3a350a",
          "md5": "cff56762f40d7129bb3914188ff1a53a"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.0.aar",
          "url": "fluttertoast_profile-1.0.aar",
          "size": 10188,
          "sha512": "43c1041b5f8359edb05e5428f3663630ed18b4926d2686e0d3e7f1f7aea5589212d3a4c379c46a7e84f06add843acbecfa2816090d3ff65e1e18b8ba1c02f666",
          "sha256": "5b15d9fba3f250dd8aa13be8e1a511b961dbb610a3d333ea5f3572c4cc97c581",
          "sha1": "26743422c796d2bc27413ad156c11c0faf3a350a",
          "md5": "cff56762f40d7129bb3914188ff1a53a"
        }
      ]
    }
  ]
}
