{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.0.aar",
          "url": "fluttertoast_release-1.0.aar",
          "size": 10191,
          "sha512": "90524ada1edf62cc1d6042aa6c93268f17769856dea91bee9d756e0cc60ddf3adcc3cf97a62d24e13035dca2b7df68d4819a76befcab443e8a7aa4d3f90cd474",
          "sha256": "80be304f30ac45d725714cec7127e49067be47dbed2b06c93af9ac90bac8d546",
          "sha1": "0d1270b12810976a6d8fb5a2b66c94c9cd1c56ae",
          "md5": "1b0c1d93c27e5df8b589f204c778ec5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-1.0.aar",
          "url": "fluttertoast_release-1.0.aar",
          "size": 10191,
          "sha512": "90524ada1edf62cc1d6042aa6c93268f17769856dea91bee9d756e0cc60ddf3adcc3cf97a62d24e13035dca2b7df68d4819a76befcab443e8a7aa4d3f90cd474",
          "sha256": "80be304f30ac45d725714cec7127e49067be47dbed2b06c93af9ac90bac8d546",
          "sha1": "0d1270b12810976a6d8fb5a2b66c94c9cd1c56ae",
          "md5": "1b0c1d93c27e5df8b589f204c778ec5c"
        }
      ]
    }
  ]
}
