{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.connectivity",
    "module": "connectivity_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 9152,
          "sha512": "698efb9e0f121370f9de6a4755ce6bcccabc524b8b175e7ce052197cddb18846a7db493455f29578c2061e95958f37363ea2a4ff899350e2a6a2a3e6c52f0c53",
          "sha256": "e0db53709f0a6e62fd8c10cfff9e3a3b2d409d7fb179682786aa915f746b3404",
          "sha1": "5dca190bf498375aa56f637d4b61126ba092c7a9",
          "md5": "7fa410bd2cf9bdbd8e40c90c72835548"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 9152,
          "sha512": "698efb9e0f121370f9de6a4755ce6bcccabc524b8b175e7ce052197cddb18846a7db493455f29578c2061e95958f37363ea2a4ff899350e2a6a2a3e6c52f0c53",
          "sha256": "e0db53709f0a6e62fd8c10cfff9e3a3b2d409d7fb179682786aa915f746b3404",
          "sha1": "5dca190bf498375aa56f637d4b61126ba092c7a9",
          "md5": "7fa410bd2cf9bdbd8e40c90c72835548"
        }
      ]
    }
  ]
}
