{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.connectivity",
    "module": "connectivity_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-1.0.aar",
          "url": "connectivity_plus_release-1.0.aar",
          "size": 9156,
          "sha512": "d97d8e115ab7e2b5ef757ef0ac9e7a9cea7d9c2ec8cac3b560e5cf83d5e3015c78cfdc7979f5208e3bded756dc7e0a050d0654f4e23bd95c6c1e4491bdb94425",
          "sha256": "f52215630ead632e8a4805be9bfbbf4ddd6f8177f8dab24472dda3f8540352eb",
          "sha1": "6faadee9e44004817e54e40ac37af4564abf68c6",
          "md5": "e7f02a883cab36b39f42cc88c750a550"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-1.0.aar",
          "url": "connectivity_plus_release-1.0.aar",
          "size": 9156,
          "sha512": "d97d8e115ab7e2b5ef757ef0ac9e7a9cea7d9c2ec8cac3b560e5cf83d5e3015c78cfdc7979f5208e3bded756dc7e0a050d0654f4e23bd95c6c1e4491bdb94425",
          "sha256": "f52215630ead632e8a4805be9bfbbf4ddd6f8177f8dab24472dda3f8540352eb",
          "sha1": "6faadee9e44004817e54e40ac37af4564abf68c6",
          "md5": "e7f02a883cab36b39f42cc88c750a550"
        }
      ]
    }
  ]
}
