{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.connectivity",
    "module": "connectivity_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_debug-1.0.aar",
          "url": "connectivity_plus_debug-1.0.aar",
          "size": 9511,
          "sha512": "272005adb8db6c24648f5cb7a089c2aea492f0a21c078aef8bdeffaf7995f5330ad3a4c46716b1c1e278f7f5d1fff904428dc030bde11cd0a048cf5d6b457963",
          "sha256": "4370dd815e83319c7856f67552176330cc67d77237fb438ee48cf0de25eaa88d",
          "sha1": "a9717158bb1f3dbce34ccc6517d843ad098cfb02",
          "md5": "7d933a4966659a3ab2546cab0fa8c32d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_debug-1.0.aar",
          "url": "connectivity_plus_debug-1.0.aar",
          "size": 9511,
          "sha512": "272005adb8db6c24648f5cb7a089c2aea492f0a21c078aef8bdeffaf7995f5330ad3a4c46716b1c1e278f7f5d1fff904428dc030bde11cd0a048cf5d6b457963",
          "sha256": "4370dd815e83319c7856f67552176330cc67d77237fb438ee48cf0de25eaa88d",
          "sha1": "a9717158bb1f3dbce34ccc6517d843ad098cfb02",
          "md5": "7d933a4966659a3ab2546cab0fa8c32d"
        }
      ]
    }
  ]
}
